<?php

namespace Picqer\Financials\Exact;

/**
 * Class Returns.
 *
 * @see https://start.exactonline.nl/docs/HlpRestAPIResourcesDetails.aspx?name=ReadFinancialReturns
 *
 * @property string $DocumentID GUID of the return document generated by EOL
 * @property float $Amount Amount in the currency of the return
 * @property string $Created The creation date of the return document
 * @property string $Currency Currency
 * @property string $Description Description
 * @property string $DocumentViewUrl Url to view the document
 * @property string $DueDate Due date of the return
 * @property string $Frequency Return frequency (M=Monthly, Q=Quarterly, A=Financial Year-Quarter, Y=Yearly)
 * @property string $PayrollDeclarationType Payroll declaration type
 * @property int $Period Return period
 * @property string $PeriodDescription Description of period
 * @property string $Request Reference to request
 * @property int $Status The status of the request (-10 - NULL, 0 - Void, 5 - Rejected, 10 - Draft, 20 - Open, 30 - Approved, 40 - Realized, 50 - Processed)
 * @property string $Subject The subject of the return document
 * @property int $Type Return Type (31 - VAT, 32-EC Sales list, 146-Payroll declaration)
 * @property int $Year Return year
 */
class Returns extends Model
{
    use Query\Findable;

    protected $primaryKey = 'DocumentID';

    protected $fillable = [
        'DocumentID',
        'Amount',
        'Created',
        'Currency',
        'Description',
        'DocumentViewUrl',
        'DueDate',
        'Frequency',
        'PayrollDeclarationType',
        'Period',
        'PeriodDescription',
        'Request',
        'Status',
        'Subject',
        'Type',
        'Year',
    ];

    protected $url = 'read/financial/Returns';
}
